# Generated by Django 5.1.1 on 2025-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beetle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text="CSS class for the beetle icon, e.g. 'fas fa-bug'", max_length=100)),
                ('description', models.TextField(help_text='Solution for getting rid of this beetle at home')),
            ],
        ),
    ]
