# Generated by Django 5.1.1 on 2025-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beetle',
            name='beetle_image',
            field=models.ImageField(blank=True, help_text='Image of the beetle', null=True, upload_to='beetle_images/'),
        ),
        migrations.AlterField(
            model_name='beetle',
            name='icon_class',
            field=models.CharField(blank=True, help_text="CSS class for the beetle icon, e.g. 'fas fa-bug'", max_length=100, null=True),
        ),
    ]
