# Generated by Django 5.1.1 on 2025-05-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
            options={
                'verbose_name': 'Подписка на новости',
                'verbose_name_plural': 'Подписки на новости',
            },
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('viewed', 'Просмотрено'), ('in_progress', 'В обработке'), ('completed', 'Услуга оказана'), ('cancelled', 'Отменена')], default='new', max_length=20),
        ),
    ]
