# Generated by Django 5.1.1 on 2025-05-16 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_newslettersubscription_alter_servicerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен подтверждения'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
    ]
